### ISSUE TITLE
The code of the modle

### ISSUE THREAD

**Issue by zhangjinrong731** [Pose-Group/MPT#1]
Will the specific code of the model be released in the future?

**Comment by zhangjinrong731** [comment]
By the way, the source connection of the code of the paper, _Motion Prediction via Joint Dependency Modeling in Phase Space_, is also failed.
https://github.com/Pose-Group/TEID

**Comment by supengxiang** [comment]
Hi Mr. Zhang, I sent an email to you some time ago. If you have any other questions, you can contact us again.

**Comment by zhangjinrong731** [comment]
非常感谢，我现在在等贵实验室解封后上传完整的代码，现在公布的代码没有trian和test部分，很多细节想再了解一下，非常感谢。

**Comment by supengxiang** [comment]
这部分公开的代码就是完整的测试代码，包括几种动作的预训练参数文件和来自S5的测试数据。prediction_model.py就是test文件，输入文件读取路径和指定起始帧就可以生成预测结果和MPJPE，然后再使用vis_modle.py（修改文件读取路径）就能生成相应预测结果的gif图。我们使用的基础骨长loss和位置loss都是来自别人公开的代码，为关节点附加的权值改编自https://github.com/BII-wushuang/Lie-Group-Motion-Prediction。

**Comment by zhangjinrong731** [comment]
这个链接也是404了
![image](https://user-images.githubusercontent.com/49579978/167322437-7bc78431-9d9a-4511-8dbf-127fd1669bc3.png)

**Comment by supengxiang** [comment]
我是能打开的，建议你再检查下。另外，那个论文也不是我的，链接真有问题的话，建议你去联系那个论文的作者。

**Comment by zhangjinrong731** [comment]
好的，非常感谢，直接点击链接多了个句号，确实是能打开的
